apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-actions
  annotations:
    github.com/project-slug: ajay-infracloud/github-actions
    backstage.io/kubernetes-id: kind-cluster-2
spec:
  type: service
  lifecycle: unknown
  owner: "group:default/guests"
