name: First Project
on: [push, workflow_dispatch]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3 
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      